typography_spectrum: 0.1867801658809185
color:
  brandStrength: 0.45358270360156894
  lightness: 0.8735035245772451
  saturation: 0.13829548610374331
  rhythmicContrast: 0.6163232503458858
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.12407938996329904
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/61df4ef1-a364-47bc-8fea-1d0c16752967.png
name: Logicad
navigation:
  - name: Esprit CAM
    url: www.espritcam.com
    type: external
title: LOGICAD SOLUTIONS
description: 'IF YOU CAD IMAGINE IT, YOU CAM BUILD IT!'
